#!/usr/bin/env bash

output=$(rfkill unblock wlan)
if [[ $? -gt 0 ]]; then
  notify-send -u normal -a rfkill "rfkill failed: $output"
fi

output=$(nmcli c u 'TETHERING_CONNECTION')
if [[ $? -gt 0 ]]; then
  notify-send -u normal -a nmcli "nmcli tethering failed: $output"
fi
  
