- pacman:
    name: "{{ os_xorg_packages }}"
    state: present

- copy:
    src: etc-X11-xorg.conf.d-00-keyboard.conf
    dest: /etc/X11/xorg.conf.d/00-keyboard.conf
    owner: root
    group: root
    mode: 0644

- systemd:
    name: lightdm
    enabled: yes